name: linux_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y autoconf automake libtool pkg-config build-essential wget

    - name: Download and build libevent 2.2.1-alpha
      run: |
        wget https://github.com/libevent/libevent/releases/download/release-2.2.1-alpha/libevent-2.2.1-alpha-dev.tar.gz
        tar -xzf libevent-2.2.1-alpha-dev.tar.gz
        cd libevent-2.2.1-alpha-dev
        ./autogen.sh
        ./configure
        make
        sudo make install
        cd ..

    - name: Export libevent path
      run: |
        echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/libevent.conf
        sudo ldconfig
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Build redsocks2 with HTTPS proxy enabled
      run: |
        make ENABLE_HTTPS_PROXY=true
