name: tagged-release

on:
  push:
    tags:
      - "release-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install depends
      run: |
        sudo apt update
        sudo apt install -y gnupg2
        echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee -a /etc/apt/sources.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
        sudo apt update
        sudo apt install -y libssl1.0-dev libevent-dev
    - name: Build
      run: make ENABLE_HTTPS_PROXY=1 ENABLE_STATIC=1
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: redsocks2
